image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/tech-support-service-1.0.0-SNAPSHOT.jar

docker-build:
  stage: docker-build
  script:
    - docker build -t $CI_DOCKER_LOGIN/tech-support-service .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/tech-support-service

docker-deploy-swarm:
 stage: docker-deploy-swarm
 script:
  - touch .env_tech_support
  - echo "SPRING_PROFILE=$SPRING_PROFILE" >> .env_tech_support
  - echo "POSTGRES_USER=$POSTGRES_USER" >> .env_tech_support
  - echo "POSTGRES_PASS=$POSTGRES_PASS" >> .env_tech_support
  - echo "POSTGRES_DB=$POSTGRES_DB" >> .env_tech_support
  - echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env_tech_support
  - docker stack deploy -c docker-compose.yaml socshared
