server:
  port: 8885

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:tech_support}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    generate-ddl: true

  # zipkin:
  #   base-url: http://zipkin:9411/
  #   service:
  #     name: ${spring.application.name}