///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package ml.socshared.service.support;
//
//import ml.socshared.service.support.integration.AbstractIT;
//import org.junit.Test;
//
//public class ApplicationContextTest extends AbstractIT {
//
//    @Test
//    public void checkContextStarts() {
//
//    }
//
//}
